CREATE TABLE challenge_attempts (
    id integer generated by default as identity primary key,
    name text not null,
    phone text not null,
    ip inet not null,
    answer integer not null,
    created_at timestamp default current_timestamp not null
);


CREATE TABLE contributors (
    id integer generated by default as identity primary key,
    name text not null,
    email text not null,
    amount integer not null,
    rewards_claimed boolean not null
);

ALTER TABLE challenge_attempts ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable insert access for all users" ON challenge_attempts
AS PERMISSIVE FOR INSERT
TO public
WITH CHECK (true);

CREATE POLICY "Enable read access for users based on their IP" ON challenge_attempts
AS PERMISSIVE FOR SELECT
TO public
USING (inet_client_addr() = ip AND inet_client_addr()::TEXT <> '127.0.0.1');

ALTER TABLE contributors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Enable read access for all users" ON contributors
AS PERMISSIVE FOR SELECT
TO public
USING (true);

